version: '2'
services:
  ca_intake:
    build: .
    command: ./bin/docker_start
    ports:
      - "3000:3000"
      - "4857:4857"
    environment:
      RAILS_ENV: development
      API_URL: "http://api:3000"
    volumes:
      - .:/ca_intake
      - ca_intake_rubygems:/ruby_gems
      - ca_intake_node_modules:/ca_intake/node_modules
    links:
      - api
  api:
    extends:
      file: ../casebook_api/docker-compose.common.yml
      service: api
    links:
      - db
      - redis
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: 'redis://redis:6379/0'
  db:
    extends:
      file: ../casebook_api/docker-compose.common.yml
      service: db
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    extends:
      file: ../casebook_api/docker-compose.common.yml
      service: api
    command: bundle exec sidekiq
    links:
      - db
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379/0'
volumes:
  ca_intake_rubygems:
  ca_intake_node_modules:
  casebook_api_rubygems:
