version: '2.1'
# 6/23/2017 - version 3.x does not support extends yet.
# - https://docs.docker.com/compose/extends/#extending-services
services:
  ca_intake:
    build: .
    command: ./bin/docker_start
    ports:
      - "3000:3000"
      - "4857:4857"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      API_URL: "http://api:3000"
      FERB_API_URL: "https://ferbapi.preint.cwds.io"
      NODE_ENV: development
      AUTHENTICATION_URL: "https://perry.preint.cwds.io/perry"
      AUTHENTICATION: ${AUTHENTICATION:-true}
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      USE_XVFB: 'true'
    volumes:
      - .:/ca_intake
      - ca_intake_rubygems:/ruby_gems
      - ca_intake_node_modules:/ca_intake/node_modules
    links:
      - api
      - redis
    tty: true
    stdin_open: true
  api:
    extends:
      file: ../intake_api/docker-compose.common.yml
      service: api
    links:
      - db
    ports:
      - "3001:3000"
    environment:
      AUTHENTICATION_URL: 'https://perry.preint.cwds.io/perry'
      AUTHENTICATION: ${AUTHENTICATION:-true}
      DORA_URL: 'https://dora.preint.cwds.io/'
      FERB_URL: 'https://ferbapi.preint.cwds.io'
    tty: true
    stdin_open: true
  db:
    extends:
      file: ../intake_api/docker-compose.common.yml
      service: db
  redis:
    image: 'redis:3.0'
    ports:
      - "6379:6379"
volumes:
  ca_intake_rubygems:
  ca_intake_node_modules:
  casebook_api_rubygems:
