version: '2'
services:
  ca_intake:
    build: .
    command: ./bin/docker_start
    ports:
      - "3000:3000"
      - "4857:4857"
    environment:
      RAILS_ENV: development
      API_URL: "http://api:3000"
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      NODE_ENV: development
    volumes:
      - .:/ca_intake
      - ca_intake_rubygems:/ruby_gems
      - ca_intake_node_modules:/ca_intake/node_modules
    links:
      - api
      - elasticsearch
    tty: true
    stdin_open: true
  api:
    extends:
      file: ../intake_api_prototype/docker-compose.common.yml
      service: api
    links:
      - db
      - redis
      - elasticsearch
    ports:
      - "3001:3000"
    environment:
      REDIS_DATABASE: 'redis://redis:6379/0'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
  db:
    extends:
      file: ../intake_api_prototype/docker-compose.common.yml
      service: db
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  sidekiq:
    extends:
      file: ../intake_api_prototype/docker-compose.common.yml
      service: api
    command: ./bin/sidekiq_start
    links:
      - db
      - redis
      - elasticsearch
    environment:
      REDIS_DATABASE: 'redis://redis:6379/0'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
  elasticsearch:
    image: 'elasticsearch:2.4'
volumes:
  ca_intake_rubygems:
  ca_intake_node_modules:
  casebook_api_rubygems:
