version: '2.1'

volumes:
  webroot:
    driver: local

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    volumes:
      - webroot:/ca_intake
    environment:
      RAILS_ENV: production
      API_URL: "http://app:3000"
      SECRET_KEY_BASE: "kiHthL9VZLTDgVbryIuVefuFqVAX9lHNvUHysYZAFaA="
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - "${HTTP_PORT}"
    volumes:
      - webroot:/ca_intake
